{"name": "test_something", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestCase' has no attribute 'data'", "trace": "self = <TestCases.test.TestCase object at 0x0000017B34FF9A48>\n\n    def test_something(self):\n        print('执行测试')\n        # 获取前置方法中产生的数据\n        # 从全局变量中获取\n        # print(EnvData.data)\n        # 从当前用例的类属性中获取\n>       print(self.__class__.data)\nE       AttributeError: type object 'TestCase' has no attribute 'data'\n\ntest.py:33: AttributeError"}, "start": 1647351320301, "stop": 1647351320301, "uuid": "27c06770-6ad3-44b5-968f-ba4dd7b6531c", "historyId": "39a634f11d7b84a6209b18be84273ba0", "testCaseId": "5c116e581817ad4319fbae74ed49d15d", "fullName": "TestCases.test.TestCase#test_something", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "DESKTOP-76566J4"}, {"name": "thread", "value": "5372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test"}]}