{"name": "test_something", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestCase' object has no attribute 'data'", "trace": "self = <TestCases.test.TestCase object at 0x00000290E74D8388>\n\n    def test_something(self):\n        print('执行测试')\n        # 获取前置方法中产生的数据\n        # 从全局变量中获取\n        # print(EnvData.data)\n        # 从当前用例的类属性中获取\n        # print(self.__class__.data)\n        # 如果当前用例对象没有同名对象属性，也可以直接从对象属性中获取\n>       print(self.data)\nE       AttributeError: 'TestCase' object has no attribute 'data'\n\ntest.py:36: AttributeError"}, "start": 1647351145997, "stop": 1647351145998, "uuid": "2446533d-1319-4573-9ac8-4ea13b22cc31", "historyId": "39a634f11d7b84a6209b18be84273ba0", "testCaseId": "5c116e581817ad4319fbae74ed49d15d", "fullName": "TestCases.test.TestCase#test_something", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "DESKTOP-76566J4"}, {"name": "thread", "value": "5320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test"}]}